### ISSUE TITLE
Fails to build on Ubuntu.

### ISSUE THREAD

**Issue by Redsandro** [damirn/rapidx2j#1]
I was curious to see if this would outperform xml-expat. But there are build problems:

```
$ npm install rapidx2j
npm http GET https://registry.npmjs.org/rapidx2j
npm http 200 https://registry.npmjs.org/rapidx2j
npm http GET https://registry.npmjs.org/rapidx2j/-/rapidx2j-0.0.7.tgz
npm http 200 https://registry.npmjs.org/rapidx2j/-/rapidx2j-0.0.7.tgz
npm http GET https://registry.npmjs.org/nan
npm http 200 https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/nan/-/nan-2.0.7.tgz
npm http 200 https://registry.npmjs.org/nan/-/nan-2.0.7.tgz

> rapidx2j@0.0.7 install /var/tests/xml2js/node_modules/rapidx2j
> node-gyp rebuild

make: Entering directory `/var/tests/xml2js/node_modules/rapidx2j/build'
  CXX(target) Release/obj.target/rapidx2j/src/rapidx2j.o
../src/rapidx2j.cc: In function ‘void InitAll(v8::Handle<v8::Object>)’:
../src/rapidx2j.cc:5:16: error: ‘NanNew’ was not declared in this scope
   exports->Set(NanNew<v8::String>("parse"), NanNew<v8::FunctionTemplate>(parse)->GetFunction());
                ^
../src/rapidx2j.cc:5:33: error: expected primary-expression before ‘>’ token
   exports->Set(NanNew<v8::String>("parse"), NanNew<v8::FunctionTemplate>(parse)->GetFunction());
                                 ^
../src/rapidx2j.cc:5:72: error: expected primary-expression before ‘>’ token
   exports->Set(NanNew<v8::String>("parse"), NanNew<v8::FunctionTemplate>(parse)->GetFunction());
                                                                        ^
../src/rapidx2j.cc:5:82: error: request for member ‘GetFunction’ in ‘parse’, which is of non-class type ‘Nan::NAN_METHOD_RETURN_TYPE(Nan::NAN_METHOD_ARGS_TYPE) {aka void(const Nan::FunctionCallbackInfo<v8::Value>&)}’
   exports->Set(NanNew<v8::String>("parse"), NanNew<v8::FunctionTemplate>(parse)->GetFunction());
                                                                                  ^
make: *** [Release/obj.target/rapidx2j/src/rapidx2j.o] Error 1
make: Leaving directory `/var/tests/xml2js/node_modules/rapidx2j/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.16.0-38-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /var/tests/xml2js/node_modules/rapidx2j
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0
```

```
$ npm --version
1.3.10
$ node --version
v0.10.25
```

**Comment by damirn** [comment]
I'm aware of this issue, it's caused by nan-2.0.x (I still haven't found time to port rapidx2j to nan-2.0.x). Try to install nan-1.9.0 (npm install nan@1.9.0) and see if that helps.

thanks for the report anyway.

**Comment by Redsandro** [comment]
It still installs it's own dependency (2.0.x) during install.

Could you update the package so it depends on `nan` `1.9.0` specifically? This way the package works without manual hacks on deployment.

**Comment by damirn** [comment]
0.0.8 has just been published to npm, please let me know if this fixes the issue for you.

**Comment by Redsandro** [comment]
Oh yes. Haven't done actual testing yet but the module installs fine now. Thanks! :+1:

**Comment by damirn** [comment]
Great. I'm more than interested in your benchmarks; if you can spare some time to share the numbers, I'd appreciate it. Thanks.

**Comment by Redsandro** [comment]
@damirn was giving this a shot, but rapidx2j seems to break on my machine.

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr
/usr/local/bin/node: line 2: 26336 Aborted                 /usr/bin/nodejs $@
```

using a simple

```
json = rapidx2j.parse(xml);
console.log(json);
```

(The xml is fine.)

**Comment by damirn** [comment]
Can you send me the xml please? Also, since this is an unrelated issue, would you mind to open a new one?

**Comment by Redsandro** [comment]
Yes. :arrow_down: https://github.com/damirn/rapidx2j/issues/2

**Comment by Redsandro** [comment]
Some initial testing parsing a 2MB xml 5 times; this looks promising.

I haven't checked the results in detail, but if there aren't any problems or caveats, I think this module should be more popular.

Of course it helps that the 0.0.9 release works out of the box now. :)

```
xml2json 0.5.1: 365ms
xml2json 0.5.1: 357ms
xml2json 0.5.1: 348ms
xml2json 0.5.1: 343ms
xml2json 0.5.1: 343ms
xml2js-expat 0.2.2: 294ms
xml2js-expat 0.2.2: 282ms
xml2js-expat 0.2.2: 325ms
xml2js-expat 0.2.2: 299ms
xml2js-expat 0.2.2: 314ms
rapidx2j 0.0.9: 154ms
rapidx2j 0.0.9: 199ms
rapidx2j 0.0.9: 180ms
rapidx2j 0.0.9: 176ms
rapidx2j 0.0.9: 175ms
```

Are there any known limitations?

**Comment by Redsandro** [comment]
Speed for `rapidx2j` for 2 MB xml seems 1.7 times faster than `node-expat`, which I previously considered the fastest node xml parser.

On files around 200 KB, it can be up to 3 times faster.

```
xml2json 0.5.1: 140ms
xml2json 0.5.1: 125ms
xml2json 0.5.1: 125ms
xml2json 0.5.1: 129ms
xml2json 0.5.1: 130ms
xml2js-expat 0.2.2: 120ms
xml2js-expat 0.2.2: 129ms
xml2js-expat 0.2.2: 102ms
xml2js-expat 0.2.2: 117ms
xml2js-expat 0.2.2: 112ms
rapidx2j 0.0.9: 28ms
rapidx2j 0.0.9: 52ms
rapidx2j 0.0.9: 30ms
rapidx2j 0.0.9: 31ms
rapidx2j 0.0.9: 30ms
```

Benchmarking in good faith; I will verify actual output later.

**Comment by damirn** [comment]
Thanks for sharing these. I've been using rapidx2j in production environment for more than 6 months w/o any issues, parsing tens of thousands of XML messages every day. I'm not aware of any limitations (besides the issues you reported) so far.
