### ISSUE TITLE
Feature request: Have parser call back

### ISSUE THREAD

**Issue by Redsandro** [damirn/rapidx2j#3]
In order for non-blocking parsing of larger XML, we would need the module to call back with the result.

Perhaps there can be an optional `callback` parameter as to not break backwards compatibility.

```
x2j.parse(xml_string, callback);
```

Preferably the callback would be node-style; i.e. error, response:
`callback(null, jsonObj)` on success
`callback(new Error('foo'))` on error

**Comment by damirn** [comment]
I guess you have huge XML files to parse :) I'll try to work on this during the weekend, it was on my roadmap, but now that it's officially requested, it will be on the top of my priority list. Thanks.

**Comment by Redsandro** [comment]
:+1: 

Yeah, I've seen chunks of up to 8MB needing to be parsed. But node can still handle simple requests simultaneously. Unless something is blocking it. :smile:

**Comment by Redsandro** [comment]
For benchmarking:

``` javascript
/*
 * Benchmarking xml to json parsers
 * @author Sander AKA Redsandro (http://www.Redsandro.com)
 */

var path        = require('path');
var util        = require('util');
var fs          = require('fs');
var q           = require('q');
    q.longStackSuppor   = true;

var xml2js      = require('xml2js');    // pure Javascript // 0.4.10
var xml2jsp     = new xml2js.Parser();

var xml2json        = require('xml2json');      // https://github.com/buglabs/node-xml2json // Fast! // 0.5.1

var x2je        = require('xml2js-expat');  // https://github.com/Poetro/node-xml2js-expat // Faster! // 0.2.2

var rapidx2j        = require('rapidx2j');      // https://github.com/damirn/rapidx2j // Fastest? // 0.0.8

var fileName        = 'huge.xml';

var pwd         = path.dirname(require.main.filename);
var file        = path.join(pwd, fileName);
var xml         = fs.readFileSync(file, 'utf8');

var timeMs;



q(true)

// Try xml2json 5 times...
.then(doXml2json)
.then(doXml2json)
.then(doXml2json)
.then(doXml2json)
.then(doXml2json)

// Try xml-expat 5 times...
.then(doExpat)
.then(doExpat)
.then(doExpat)
.then(doExpat)
.then(doExpat)

// Try rapidx2j 5 times...
.then(doRapid)
.then(doRapid)
.then(doRapid)
.then(doRapid)
.then(doRapid)


.then(function(json) {
    console.log('Done.');

    return;
})


.fail(function(e) {
    console.log('Failed with error. :(');
    console.log(e.stack);
})
.done();


function doExpat() {
    return q.nfcall(function(cb) {
        var json;

        var modName = 'xml2js-expat 0.2.2';
        console.time(modName);

        var parser = new x2je.Parser(function(result, error) {
            if (!error) {
                json = result;
                console.timeEnd(modName);
            }
            else {
                console.error(error);
            }
        });

        if (parser.parseString(xml)) {
            cb(null, json);
        } else {
          cb(new Error(util.format('node-xml2js-expat: parse error: "%s"', parser.getError() )));
        }
    }); 
}

function doRapid() {
    return q.nfcall(function(cb) {
        var json;   
        var modName = 'rapidx2j 0.0.9';

        //console.log(util.format('Trying %s...', modName));
        console.time(modName);

        try {
            json = rapidx2j.parse(xml);
            //console.log(json);
            console.timeEnd(modName);
            cb(null, json);
        }
        catch (e) {
            cb(e);
        }
    }); 
}

function doXml2json() {
    return q.nfcall(function(cb) {
        var json;   
        var modName = 'xml2json 0.5.1';

        console.time(modName);

        try {
            json = xml2json.toJson(xml, {object: true});
            // console.log(JSON.stringify(json));
            console.timeEnd(modName);
            cb(null, json);
        }
        catch (e) {
            cb(e);
        }
    }); 
}
```

**Comment by damirn** [comment]
I like this tool! Can you share some real world numbers together with XMLs you used?

**Comment by Redsandro** [comment]
```
xml2json 0.5.1: 629ms
xml2json 0.5.1: 607ms
xml2json 0.5.1: 612ms
xml2json 0.5.1: 602ms
xml2json 0.5.1: 604ms
xml2js-expat 0.2.2: 526ms
xml2js-expat 0.2.2: 487ms
xml2js-expat 0.2.2: 527ms
xml2js-expat 0.2.2: 491ms
xml2js-expat 0.2.2: 526ms
rapidx2j 0.0.9: 270ms
rapidx2j 0.0.9: 321ms
rapidx2j 0.0.9: 332ms
rapidx2j 0.0.9: 295ms
rapidx2j 0.0.9: 294ms
```

[test_2mb.xml](https://gist.github.com/Redsandro/53072e6fc35af2847300)

**Comment by damirn** [comment]
I have just committed the C++ part for handling callback. I will not push this to npm, until you run some tests and say that all looks OK.

**Comment by Redsandro** [comment]
How do I gyp compile that from local files using npm?

**Comment by damirn** [comment]
use node-gyp:
node-gyp rebuild

**Comment by Redsandro** [comment]
hmm..

```
$ node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@0.10.10
gyp info using node@0.10.25 | linux | x64
gyp info spawn python
gyp info spawn args [ '/usr/share/node-gyp/gyp/gyp',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/var/www/tests/xml2js/node_modules/rapidx2j/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/share/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/include/nodejs/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/usr/include/nodejs',
gyp info spawn args   '-Dmodule_root_dir=/var/www/tests/xml2js/node_modules/rapidx2j',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/var/www/tests/xml2js/node_modules/rapidx2j/build'
  CXX(target) Release/obj.target/rapidx2j/src/rapidx2j.o
  CXX(target) Release/obj.target/rapidx2j/src/parser.o
../rapidx2j/src/parser.cc:128:29: error: ‘FunctionCallbackInfo’ in namespace ‘v8’ does not name a type
 static bool parseArgs(const v8::FunctionCallbackInfo<v8::Value> &args)
                             ^
../rapidx2j/src/parser.cc:128:33: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
 static bool parseArgs(const v8::FunctionCallbackInfo<v8::Value> &args)
                                 ^
../rapidx2j/src/parser.cc:128:53: error: expected ‘,’ or ‘...’ before ‘<’ token
 static bool parseArgs(const v8::FunctionCallbackInfo<v8::Value> &args)
                                                     ^
../rapidx2j/src/parser.cc: In function ‘bool parseArgs(int)’:
../rapidx2j/src/parser.cc:130:7: error: ‘args’ was not declared in this scope
   if (args.Length() < 1)
       ^
../rapidx2j/src/parser.cc:135:7: error: ‘args’ was not declared in this scope
   if (args.Length() >= 2)
       ^
../rapidx2j/src/parser.cc: In function ‘v8::Handle<v8::Value> parse(const v8::Arguments&)’:
../rapidx2j/src/parser.cc:171:22: error: cannot convert ‘const v8::Arguments’ to ‘int’ for argument ‘1’ to ‘bool parseArgs(int)’
   if (!parseArgs(args))
                      ^
../rapidx2j/src/parser.cc: In function ‘v8::Handle<v8::Value> parseAsync(const v8::Arguments&)’:
../rapidx2j/src/parser.cc:245:22: error: cannot convert ‘const v8::Arguments’ to ‘int’ for argument ‘1’ to ‘bool parseArgs(int)’
   if (!parseArgs(args))
                      ^
make: *** [Release/obj.target/rapidx2j/src/parser.o] Error 1
make: Leaving directory `/var/www/tests/xml2js/node_modules/rapidx2j/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.16.0-38-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /var/www/tests/xml2js/node_modules/rapidx2j
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
```

Is this me?

**Comment by damirn** [comment]
node 0.10.25? i'll need to setup that one and give it a try..

**Comment by Redsandro** [comment]
Yeah we have `0.10` running on our servers, so I run the same version locally for compatibility reasons.

**Comment by damirn** [comment]
Try now, just made a quick fix.

**Comment by Redsandro** [comment]
Build works! :+1: 

Give me some minutes to play around with it.

**Comment by Redsandro** [comment]
Works! :smile: 

Fails on some parameters tho. I suggest to reintroduce strict checking. Can also improve some readability. I fixed it for you, you can review: https://github.com/damirn/rapidx2j/pull/6

**Comment by damirn** [comment]
Merged. Do you see any other failures? btw, feel free to add yourself as a contributor to readme.md, i'll merge the pull request gladly.

**Comment by Redsandro** [comment]
Nice. :)  Where would I add this? I can add it to the current PR.

**Comment by Redsandro** [comment]
> Do you see any other failures? 

Checking ...

**Comment by Redsandro** [comment]
@damirn ok I found a problem with values used in your tests because of the way I typecast. I think I misunderstood one option.

**Comment by Redsandro** [comment]
@damirn `empty_tag_value` is the value for empty tags in stead of wether or not empty tags should be parsed?

**Comment by Redsandro** [comment]
The test passes but that's because assert doesn't compare types.

**Comment by Redsandro** [comment]
Fixed here: https://github.com/damirn/rapidx2j/pull/8

**Comment by damirn** [comment]
empty_tag_value is the value for empty tags

**Comment by Redsandro** [comment]
I would change the default to something semantically relevant like `null` or `undefined`.

The option does not allow to be set to `undefined`. Fix: https://github.com/damirn/rapidx2j/pull/11

Apart from that, I think it's ready for push to `npm`. The only issue I notice is not relevant to this callback thing:

`Parse_float` to `false` stops parsing int, even if `parse_int` is `true`. A bit ambiguous or confusing. But not a big problem.

**Comment by Redsandro** [comment]
Yeah, `parse_int_numbers` seems to do exactly the same as `parse_float_numbers`.

**Comment by Redsandro** [comment]
I've created a separate issue for that. For me it is not important.
https://github.com/damirn/rapidx2j/issues/9

**Comment by Redsandro** [comment]
You can merge above fix https://github.com/damirn/rapidx2j/issues/9 and https://github.com/damirn/rapidx2j/pull/11 and then push this to `npm`. The callback functionality is awesome! :+1: 

---

In order to make this parser easy to use and to replace other parsers with just a configuration change, I've created issues for the features that would be needed for this.
- [Feature: `empty_attr_value`](https://github.com/damirn/rapidx2j/issues/12)
- [Feature: `attr_key` to change attribute prepended identifier](https://github.com/damirn/rapidx2j/issues/13)
- [Feature: Have attributes collected in single subobject.](https://github.com/damirn/rapidx2j/issues/14)

This would add the following extra options (with some defaults for backwards compatibility):

```
{
    empty_attr_value: null,
    attr_key: '@',
    tag_key: '$',
    collect_attrs: false
}
```
